SEProject/Views/Flashcard/CreateSampleFlashcard.cshtml
SEProject/flashcards.json
SEProject/wwwroot/css/flashcard.css
SEProject/wwwroot/js/flashcard.js

I have added a JavaScript file for revealing the answer when the button is clicked. Also added some basic CSS for cosmetic reasons.

Reveal answer when button is clicked

---

SEProject/Views/Home/Index.cshtml
SEProject/Views/Shared/_Layout.cshtml

Just minor cleanups before the Wednesday PSI class

Updated index page, header and footer

---

SEProject/Controllers/FlashcardController.cs
SEProject/Services/FlashcardService.cs

Minor changes in filenames, formatting, etc. across FlashcardService and FlashcardController.

Minor fixes

---

SEProject/Services/FlashcardService.cs
SEProject/flashcards.json

Fixing file save (.json) issue.

fixes .json alignment when deleting file

---

SEProject/Controllers/FlashcardController.cs
SEProject/Views/Flashcard/CreateSampleFlashcard.cshtml
SEProject/Views/Flashcard/EditFlashcard.cshtml
SEProject/flashcards.json
SEProject/wwwroot/css/flashcard.css
SEProject/wwwroot/js/editFlashcard.js

Implemented editing each flashcard feature.

Editing flashcard feature

---

SEProject/Controllers/FlashcardController.cs
SEProject/Data/Flashcards/2c076dbd-2e01-4f4d-bd95-4c56f678e08a.json
SEProject/Data/Flashcards/52cc1d3c-af50-44ab-ae76-ff92d4bf4f9e.json
SEProject/Data/Flashcards/74144fb3-434a-49f0-9582-04bd96c81805.json
SEProject/Data/Flashcards/8777d10b-262f-4874-9d54-6a0bf508586d.json
SEProject/Data/Flashcards/98ad46db-40f0-4b1d-8f02-16273fb2f076.json
SEProject/Data/Flashcards/b7f8798b-3bc7-4394-af93-46f582152f4d.json
SEProject/Data/Flashcards/c6c0fc08-ead0-4a38-b4d3-4f31f0482f6e.json
SEProject/Data/Flashcards/e432178e-456d-4d38-86b6-4a7c9c35e187.json
SEProject/Data/Flashcards/f7bce3ac-9333-4a2b-81a6-7ecf52fecc5c.json
SEProject/Services/FlashcardService.cs

Modified flashcard storage. Flashcards are now stored in the newly created directory 'Data/Flashcards/' as individual JSON files with the flashcard's GUID as the filename.

Modified flashcard storage

---

SEProject/Controllers/FlashcardController.cs
SEProject/Program.cs
SEProject/Services/FlashcardService.cs
SEProject/Services/IFlashcardFileIOService.cs

FlashcardController now uses interface IFlashcardFileIOService instead of the class FlashcardService do save and load flashcards.
FlashcardService now implements IFlashcardFileIOService. In Program.cs FlashcardService is injected as an instance of IFlashcardFileIOService.

Dependency injection with flashcard service

---

SEProject/Controllers/FlashcardController.cs
SEProject/Data/Flashcards/2c076dbd-2e01-4f4d-bd95-4c56f678e08a.json
SEProject/Data/Flashcards/52cc1d3c-af50-44ab-ae76-ff92d4bf4f9e.json
SEProject/Data/Flashcards/SEProject/Data/Flashcards/2c076dbd-2e01-4f4d-bd95-4c56f678e08a.json
SEProject/Program.cs
SEProject/Services/FlashcardFileIOService.cs
SEProject/Services/IFlashcardDataHandler.cs

Changed IFlashcardFileIOService to IFlashcardDataHandler. The service which implements it is now IFlashcardFileIOService.

Changed flashcard data handling interface.

---

SEProject/Controllers/FlashcardController.cs
SEProject/Data/Flashcards/787727a1-c176-4df2-8282-06cd235e7569.json
SEProject/Data/Flashcards/8777d10b-262f-4874-9d54-6a0bf508586d.json
SEProject/Data/Flashcards/98ad46db-40f0-4b1d-8f02-16273fb2f076.json
SEProject/Data/Flashcards/c6c0fc08-ead0-4a38-b4d3-4f31f0482f6e.json
SEProject/Data/Flashcards/d0e74d39-3ede-4c44-9400-83a7e37ac6c9.json
SEProject/Data/Flashcards/f7bce3ac-9333-4a2b-81a6-7ecf52fecc5c.json
SEProject/Data/Flashcards/ff2ff382-9d11-45bd-9aa8-4bf197b35354.json
SEProject/Models/Flashcard.cs
SEProject/Models/FlashcardComparer.cs
SEProject/Views/Flashcard/CreateSampleFlashcard.cshtml
SEProject/Views/Flashcard/EditFlashcard.cshtml

Changed names of all properties in the Flashcard model and modified any code that uses them to fit property naming scheme (First letter capitalized CamelCase)

Fixed property naming in Flashcard model.

---

SEProject/Controllers/FlashcardController.cs
SEProject/Services/FlashcardFileIOService.cs
SEProject/Services/IFlashcardDataHandler.cs

Added LoadFlashcard(Guid id) to IFlashcardDataHandler.
Implemented LoadFlashcard(Guid id) in FlashcardFileIOService which loads a single flashcard by the given GUID.
Changed EditFlashcard(Guid id) to use the new LoadFlashcard(Guid id) method.

Added method to load single flashcard by GUID

---

SEProject/Controllers/FlashcardController.cs
SEProject/Data/Flashcards/39f73135-d0fc-4596-938f-15823178a193.json
SEProject/Data/Flashcards/3ddd6e4b-cc4f-4975-8ae1-5958d606d527.json
SEProject/Data/Flashcards/595e0141-c2f1-4e48-b82c-d4dd6757c4f9.json
SEProject/Data/Flashcards/787727a1-c176-4df2-8282-06cd235e7569.json
SEProject/Data/Flashcards/8777d10b-262f-4874-9d54-6a0bf508586d.json
SEProject/Data/Flashcards/98ad46db-40f0-4b1d-8f02-16273fb2f076.json
SEProject/Data/Flashcards/c6c0fc08-ead0-4a38-b4d3-4f31f0482f6e.json
SEProject/Data/Flashcards/d0e74d39-3ede-4c44-9400-83a7e37ac6c9.json
SEProject/Data/Flashcards/e6de3211-7553-43d2-8241-998a3c0bcced.json
SEProject/Data/Flashcards/f7bce3ac-9333-4a2b-81a6-7ecf52fecc5c.json
SEProject/Data/Flashcards/ff2ff382-9d11-45bd-9aa8-4bf197b35354.json
SEProject/Models/Flashcard.cs
SEProject/Models/FlashcardComparer.cs
SEProject/Views/Flashcard/CreateSampleFlashcard.cshtml
SEProject/Views/Flashcard/EditFlashcard.cshtml
SEProject/wwwroot/css/flashcard.css

Fixed the text wrap bug. Now a big words will be cut in half if they don't fit in the flashcard cointainer.

Fixing flashcard text bug

---

SEProject/Controllers/FlashcardController.cs
SEProject/Data/Flashcards/71bdd1d5-d186-48ce-a79e-c8d949bbd118.json
SEProject/Data/Flashcards/f7bce3ac-9333-4a2b-81a6-7ecf52fecc5c.json
SEProject/Models/Flashcard.cs
SEProject/Models/LogEntry.cs
SEProject/Program.cs
SEProject/Services/FlashcardFileIOService.cs
SEProject/Services/ILoggingHandler.cs
SEProject/Services/LoggingService.cs
SEProject/log.txt

Implemented these project requirements by adding a logging functionality

Record, named and optional argument usage

---

SEProject/Services/FlashcardPackFileIOService.cs

I have changed FlashcardPackFileIOService.cs to use stream for the requirement.

Implemented Streams, I think

---

SEProject/Controllers/FlashcardPackController.cs
SEProject/Services/FlashcardPackFileIOService.cs
SEProject/Services/LoggingService.cs
SEProject/log.txt
SEProject\log.txt
SEProjectlog.txt

Configured logger for the Flashcard Packs.

Adding logger to the flashcardpack controller

---

SEProject/Services/FileStreamJsonExtensions.cs
SEProject/Services/FlashcardPackFileIOService.cs

Added FileStream extension methods Serialize and Deserialize for easier Json serialization and deserialization.
Modified FlashcardPackFileIOService to use these new methods.
Extension methods are in PSI2023SemesterProject\SEProject\Services\FileStreamJsonExtensions.cs, in the static class FileStreamJsonExtensions.

Added FileStream extension methods for easier Json serialization and deserialization

---

SEProject/Controllers/FlashcardController.cs
SEProject/Controllers/FlashcardPackController.cs
SEProject/Models/LogEntry.cs
SEProject/Services/LoggingService.cs

Modified LogEntry to make more use of named and optional arguments

Named and optional arguments

---

SEProject/Controllers/FlashcardController.cs
SEProject/Controllers/FlashcardPackController.cs
SEProject/Data/FlashcardPacks/f22bb0da-85ea-4335-b7a0-9b4c0b15a1d2.json
SEProject/Enums/DifficultyLevel.cs
SEProject/Models/Flashcard.cs
SEProject/Models/LogEntry.cs
SEProject/Models/UserParameters.cs
SEProject/Services/LoggingService.cs
SEProject/log.txt

1. Struct and enum have their own files.
2. Added an exception logging into a file. And now it should use optional arguments.
3. Separated Flashcard actions from FlashcardPackController. Now every action that is related to Flashcards only have their own controller.

Changes for the 0.1 points

---

SEProject/Controllers/FlashcardController.cs
SEProject/Controllers/FlashcardPackController.cs
SEProject/Migrations/20231108152143_initial.Designer.cs
SEProject/Migrations/20231108152143_initial.cs
SEProject/Models/FlashcardPack.cs
SEProject/Models/LogEntry.cs
SEProject/Services/FlashcardIOService.cs
SEProject/Services/FlashcardPackFileIOService.cs
SEProject/log.txt

There is still a couple of warnings left.

Warning fixes

---

SEProject/Controllers/FlashcardPackController.cs
SEProject/Events/FlashcardEventArgs.cs
SEProject/Events/FlashcardPackEventArgs.cs
SEProject/Services/FlashcardIOService.cs
SEProject/Services/FlashcardPackFileIOService.cs
SEProject/Services/IFlashcardIOService.cs
SEProject/Services/IFlashcardPackDataHandler.cs

Made events to log everything to a file.

Adding events

---

SEProject/Controllers/FlashcardController.cs
SEProject/Views/Flashcard/PresentFlashcard.cshtml
SEProject/wwwroot/css/presentFlashcard.css
SEProject/wwwroot/js/presentFlashcard.js

Implemented toggling functionality to update the 'isFavorite' status of flashcards.

isFavorite button

---

SEProject/Controllers/FlashcardPackController.cs
SEProject/Exceptions/FlashcardNotFoundException.cs
SEProject/Exceptions/FlashcardPackNotFoundException.cs
SEProject/Program.cs
SEProject/Services/FlashcardIOService.cs
SEProject/Services/FlashcardPackFileIOService.cs
SEProject/Services/FlashcardPackIOService.cs
SEProject/log.txt

I have created a custom exception class. 
1. FlashcardNotFound
2. Flashcard**Pack**NotFound
If **Flashcard** or **FlashcardPack** is not found when trying to remove, then the custom exception fill be thrown and handled in a controller.

REQUIREMENT: Custom exception throwing/handling and logging to log.txt file

---

SEProject/Views/Flashcard/PresentFlashcard.cshtml
SEProject/Views/FlashcardPack/AddFlashcard.cshtml
SEProject/Views/FlashcardPack/CreateSampleFlashcardPack.cshtml
SEProject/Views/FlashcardPack/EditFlashcard.cshtml
SEProject/log.txt
SEProject/wwwroot/css/textArea.css
SEProject/wwwroot/js/editFlashcardPack.js
SEProject/wwwroot/js/validateForm.js

When you edit **FlashcardPack** name, you get a text box on the flashcardPack that you want to update.

Feature modifications

---

SEProject.sln
SEProject/EventServices/FlashcardEventService.cs
SEProject/EventServices/FlashcardPackEventService.cs
SEProject/Models/LogEntry.cs
SEProject/Program.cs
SEProject/SEProject.csproj
SEProject/Services/ILoggingHandler.cs
SEProjectTests/FlashcardEventServiceTests.cs
SEProjectTests/FlashcardPackEventServiceTests.cs
SEProjectTests/LoggingServiceTests.cs
SEProjectTests/SEProjectTests.csproj
SEProjectTests/Usings.cs

Added logger and eventService tests

---

SEProjectTests/FlashcardIOServiceTests.cs
SEProjectTests/FlashcardPackEventServiceTests.cs
SEProjectTests/FlashcardPackIOServiceTests.cs
SEProjectTests/LoggingServiceTests.cs
SEProjectTests/SEProjectTests.csproj

Added more tests for services.
Now the total coverage is 41%

Added tests for FlashcardIOService and FlashcardPackIOService

---

SEProjectTests/FlashcardIOServiceTests.cs
SEProjectTests/FlashcardPackIOServiceIntegrationTests.cs
SEProjectTests/FlashcardPackIOServiceTests.cs

I have added one integration test and fixed the unit tests that were using database.

Added integration tests

---

SEProject/Controllers/FlashcardPackController.cs
SEProject/Services/FlashcardPackIOService.cs
SEProject/Views/FlashcardPack/ViewFlashcardPack.cshtml
SEProjectTests/FlashcardPackIOServiceIntegrationTests.cs

Everytime a new flashcard is being added or edited the question should have a question mark at the end.
Flashcard missing question mark at the end will not be saved in the database and alert will be showed to user.

Added more integration tests and regex usage

---

SEProject.sln
SEProject/Controllers/UserController.cs
SEProject/Models/User.cs
SEProject/Program.cs
SEProject/Services/IUserService.cs
SEProject/Services/UserService.cs
SEProject/Views/Shared/_Layout.cshtml
SEProject/Views/User/SignUp.cshtml
SEProject/wwwroot/css/form.css

Created a sign-up page and the functionality that takes in the user's input and creates a new user (only locally, does not have the functionality to put the user to the DataBase)

Sign up page

---

SEProject/Controllers/UserController.cs
SEProject/EventArguments/UserEventArgs.cs
SEProject/EventServices/IUserEventService.cs
SEProject/EventServices/UserEventService.cs
SEProject/Models/DatabaseContext.cs
SEProject/Models/User.cs
SEProject/Program.cs
SEProject/Services/IUserService.cs
SEProject/Services/UserService.cs

Whenever a new user signs-up a new row to database is being inserted.
Added events to work with logger, when new user is being added. We can use it later, when we make changes with users.

Connect user to data base

---

SEProject/Controllers/FlashcardPackController.cs
SEProject/Controllers/UserController.cs
SEProject/EventServices/UserEventService.cs
SEProject/Models/DatabaseContext.cs
SEProject/Services/FlashcardPackIOService.cs
SEProject/Services/IFlashcardPackDataHandler.cs
SEProject/Services/UserService.cs
SEProject/Views/FlashcardPack/CreateSampleFlashcardPack.cshtml

Users can only access their flashcard packs.

Users can see their packs

---

DatabaseAPI/DatabaseAPI/Controllers/FlashcardPackController.cs
SEProject/Controllers/FlashcardPackController.cs
SEProject/Program.cs
SEProject/Views/FlashcardPack/EditFlashcard.cshtml

New HttpClient objects are acquired using a IHttpClientFactory, which is supplied to the controller using DI.
Removed unnecessary string conversions when working with user authentification.
Leveraged HttpClient extension methods to shorten the code wherever possible.
Removed (in my opinion) unnecessary http response handling code in favor of implicit handling with try/catch blocks.

Refactored FlashcardPackController in frontend (SEProject)
